### PR TITLE
Update app icon

### PR DESCRIPTION
**Pull request by lobau**
Love the app, but the app icon could be improved to follow more closely the Gnome app icon guidelines https://developer.gnome.org/hig/stable/icon-design.html.en

App Icon Preview

### CODE REVIEW

**Comment by jannuary** [comment]
Great work! If I were to nitpick though, the [perspective](https://teams.pages.gitlab.gnome.org/Design/hig-www/guidelines/app-icons.html#perspective) seems a bit off

**Comment by lobau** [comment]
This is correct. To follow the correct Gnome perspective the bottom should be a circle, which is obviously impossible.
I can try a version where the film roll is on its side to avoid the problem.

**Comment by lobau** [comment]
I am actually liking the vertical orientation quite a bit.
Happy to update the PR if @weclaw1 prefers this version too

App Icon Preview Alt

**Comment by enaut** [comment]
mhm the second version is a little "printer-like" meaning it has about the same silhouette as a printer icon. Especially the symbolic icon is easily mistaken I guess... So I like the first one better.

**Comment by weclaw1** [comment]
I think the first version is better. The second one would be harder to find and as @enaut said it looks like a printer.
Thank you for the icon. My artistic abilities are pretty limited and your icon is a big improvement over mine :)

**Pull request merged**
